import Head from 'next/head'
import { Container } from '@mui/material'
import TodoList from '@/components/TodoList'



export default function Home() {
  return (
    <Container maxWidth="md">
      <Head>
        <title>TO DO APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoList/>
      
    </Container>
  )
}
